[package]
name = "yorickrt"
version = "0.1.0"
authors = ["Edd Barrett <vext01@gmail.com>", "Laurence Tratt <laurie@tratt.net>"]

[dependencies]
hwtracer = {git = "https://github.com/softdevteam/hwtracer"}
